### PR TITLE
Add more flags

### PR DESCRIPTION
**Pull request by Cretezy**

### CODE REVIEW

**Comment by CraftThatBlock** [comment]
Needed more flags for a personal project, felt like upstream might like it

**Comment by CraftThatBlock** [comment]
After this is merged, I can push the implementation for https://github.com/flyingrub/scdl/issues/87 which I have finished.

**Comment by Cretezy** [comment]
Any updates?

**Comment by flyingrub** [comment]
i can't merge your PR from here... It has conflict with master. I also don't like the fact it add another global variable. :/

**Comment by flyingrub** [comment]
I'm closing this one due to merge conflict. Feel free to open a new PR if you have some time.

**Pull request closed without merging**
