### PR TITLE
New sync option

### PR DESCRIPTION
**Pull request by hunkyburrito**
Downloads and Removes changed tracks in a playlist (compared to last archive file) #154 #299

### CODE REVIEW

**Comment by i3asm** [comment]
These changes look great. But you added too many features in one pull request, you should separate it to make it easier for everyone to validate the changes.

Anyway, Thank you for this.

**Comment by hunkyburrito3** [comment]
Got it, will definitely keep that in mind in the future. This was my first time making a PR (and using git), so still learning the ropes lol.

**Comment by Seme4eg** [comment]
Is this PR stuck? I also need 'sync' feature a lot.

**Comment by hunkyburrito** [comment]
I have updated this PR so it only introduces the sync feature. The last 2 commits are the only relevant ones now.

**Comment by Seme4eg** [comment]
@hunkyburrito, i tested this feature, works great, but is there a way or enough reason to make sync option work now with just playlist sync, but with profile sync? cuz i have like 20 playlists on my profile and usually when i want to update my local sc profile copy i run `scdl -l https://soundcloud.com/my-nickname -p --addtimestamp --addtofile --original-art --download-archive archive.txt -c`, which just downloads all my playlists 1 by 1. With current version of sync feature you added i need to manyally run sync for each of my playlist, which is tedious.

**Comment by hunkyburrito** [comment]
I've thought about adding that functionality, but with how the archive files are currently implemented it's tough to keep track of which tracks are from which playlists and sync them. I could add a workaround that automatically makes an archive file for each playlist, but I don't think cluttering directories with like 20 archive files is the right direction. The other way that I've thought of is splitting up the archive file with playlist id or some other identifier to separate tracks. It'll probably take me a while to implement anything though.

**Comment by tommiekerssies** [comment]
when will this be merged?

**Pull request merged**
