### PR TITLE
replace md with rst

### PR DESCRIPTION
**Pull request by xnrx**

### CODE REVIEW

**Comment by faisalburhanudin** [comment]
dear maintenance please accept this, and change setup.py to not use pypandoc. instead using this README.rst direcly

because pypandoc is really big package and not support python3.5 (i using this version)

**Comment by flyingrub** [comment]
https://github.com/flyingrub/scdl/commit/500cae10caad60b996b833ed84dca88dccf3b889

**Comment by flyingrub** [comment]
i prefer markdown

**Comment by faisalburhanudin** [comment]
great

**Pull request closed without merging**
