### PR TITLE
check track title for artist

### PR DESCRIPTION
**Pull request by justinTM**

### CODE REVIEW

**Comment by flyingrub** [comment]
I think this should perhaps be added as an option ?

**Comment by justinTM** [comment]
Done!

**Comment by flyingrub** [comment]
Did you tested it with `--addtofile` option ? And also could you update `Readme.md` ? :)

**Comment by justinTM** [comment]
I checked --addtofile and it doesn't conflict.; just sets the ID3 tags not the filename. Also added in the README update :)

**Comment by justinTM** [comment]
Done, btw 🎉

**Pull request merged**
