### PR TITLE
Fixed application helptext

### PR DESCRIPTION
**Pull request by gs11**
Polished the language for some parameters that was a bit confusing.

### CODE REVIEW

**Comment by flyingrub** [comment]
thanks for your PR !
I don't know if the rewrite of `--debug` and `--error` is more explicit.
Can you leave it as they were ?

**Comment by gs11** [comment]
```
--error               Only print debug information (Error/Warning)
```
This sounds like it is debug information while in reality it's log level ERROR (not warnings)?
```
--debug               Print every information and
```
This sentence is incomplete but means log level DEBUG?

**Comment by flyingrub** [comment]
Right I didn't catch that. Thanks ! 🎉

**Comment by flyingrub** [comment]
could you open a follow up PR to fix the help text on `readme.md` ?

**Comment by gs11** [comment]
Sure, see PR #216

**Pull request merged**
