### PR TITLE
Sync Update: Simplified Removal Process

### PR DESCRIPTION
**Pull request by hunkyburrito**
Instead of trying to find the filename of each ID that needs to be removed, I decided to just remove all the files that are not in the online playlist. This should address #437 now that I don't need to guess the filename.

### CODE REVIEW

**Comment by Seme4eg** [comment]
I tested this on my 18 playlists, the error doesn't occur any more, but there is no more 'Removed {trackname}' message, which i'd still like to see.
https://github.com/flyingrub/scdl/pull/438/files#diff-35e2cac53dc8ee863183c5a1405f67e69a662ea833dbb3c2428b985804aa9bd6L429

Just to know which tracks got removed

**Comment by Seme4eg** [comment]
New error appeared 
Can reproduce only on your master branch

**Comment by CosmicSage** [comment]
why not merged yet? @hunkyburrito

**Comment by hunkyburrito** [comment]
I don't have write access so I am waiting on it being merged as well.

**Comment by CosmicSage** [comment]
seems like the owner isn't interested in PRs??

**Comment by Seme4eg** [comment]
We don't know
Anyway you can install hunky's version from pip

**Comment by CosmicSage** [comment]
I was thinking of adding a feature but maybe I should stick with bash scripts given this situation.

**Pull request merged**
