### PR TITLE
verify downloaded size matches content-length

### PR DESCRIPTION
**Pull request by r00t-**
basic fix for https://github.com/flyingrub/scdl/issues/248

### CODE REVIEW

**Comment by flyingrub** [comment]
I would prefer a more meaningful message, also we could use our `logger` to display the message, and then exit.

**Comment by r00t-** [comment]
the error-handling there is actually broken and crashes the program (`raise` does not take a string argument.)

feel free to add your own error handling, or make a suggestion on how to handle it. (the error-handling in scdl in general isn't the greatest :\ )
this was mostly intended to demonstrate the fix.

**Comment by r00t-** [comment]
@flyingrub: now with "proper" error handling, enjoy.

(note that if we don't rename the incomplete file, it will be left in /tmp... my tmp is full of stale tmpfiles with useless names, left by scdl in various situations... another issue)

**Comment by flyingrub** [comment]
Is there any interest in keeping an incomplete file ?

**Comment by r00t-** [comment]
depends on the user's connection's throughput (and maybe traffic quota).
if you just downloaded 90% of a 1gb stream through your 56k modem, or billed-by-volume mobile link, you're going to be very angry at the program discarding the data.
but ofcourse it's of limited use without an option to resume...

**Comment by r00t-** [comment]
removed the moving, so you can merge it.

**Comment by flyingrub** [comment]
thanks :)

**Pull request merged**
