### PR TITLE
fixed the download from stream function, works now

### PR DESCRIPTION
**Pull request by Spotlight0xff**
Hey, I added the functionality of the stream download.
Please tell me, if I've something wrong :)

### CODE REVIEW

**Comment by flyingrub** [comment]
i would prefer to use the wrapper, i let it open the time to check if it's still not possible.

**Comment by Spotlight0xff** [comment]
Thanks for your response, will update in a while. I don't have much spare time as exams are coming up :/ But yea, the wrapper doesn't work for the stream, tried it ofc.

**Comment by Spotlight0xff** [comment]
Hm, I don't really know what you expect. There is no option to use the offset method (I presume that's what you mean with "10 by 10"). It fetches the 10 latest tracks, provides a cursor-URL with which I can download the next 10 tracks from the stream. So how should I optimize it? :)

**Comment by flyingrub** [comment]
i'm working on another project for now ... https://github.com/flyingrub/TamTime
i will add this when i find time ;)

**Pull request closed without merging**
