### PR TITLE
Added user-agent to requests

### PR DESCRIPTION
**Pull request by def-hash**
Many requests were failing due to a 403 Forbidden error, and the community determined it was due to a lack of a User-Agent in request headers. I added a USER_AGENT variable to __init__.py

### CODE REVIEW

**Comment by gpchelkin** [comment]
One more `requests.get` here :smile: 
https://github.com/def-hash/scdl/blob/97368ec8c775d8641a6b4d9bad27381d2579f83f/scdl/scdl.py#L709

**Comment by def-hash** [comment]
> One more `requests.get` here 😄 https://github.com/def-hash/scdl/blob/97368ec8c775d8641a6b4d9bad27381d2579f83f/scdl/scdl.py#L709

thanks!

**Comment by gpchelkin** [comment]
@def-hash FYI you could have just committed one more time to the same branch `user-agent-fix` and it would have appeared in this very PR, no need to recreate it :)

**Comment by def-hash** [comment]
@def-hash Sorry, I'm new to this.  I had deleted the repository yesterday and wasn't sure how to only commit to that branch. Thanks :)

**Pull request closed without merging**
