### PR TITLE
Set tag for tracknumber when downloading playlist

### PR DESCRIPTION
**Pull request by insilmaril**

### CODE REVIEW

**Comment by flyingrub** [comment]
I think we could create a playlist object instead of 3 arguments.

**Comment by insilmaril** [comment]
That's my first python code, I'm open to any improvements ;-)

**Comment by insilmaril** [comment]
Another idea: A commandline option to prefix filename with tracknumber would also come handy, because even mortplayer or a other commandline programs (players, conversion tools, ...) could use it easily...

**Comment by flyingrub** [comment]
Mortplayer support m3u. :) You only have to read the playlist to have the track in the right order.

**Comment by flyingrub** [comment]
This PR has now has merge conflict with master. I'm closing it for now. Feel free to open an issue or a new PR.

**Comment by saphtea** [comment]
Would love to see this reapproached and implemented. My likes list order in particular is important because I listened through my likes list all the time as I grew up, so certain grouped tracks in the likes playlist order represent different times of my life and reminders for me. I hate using soundcloud now, so would love to have a way to replicate the order of my likes list via metadata or otherwise for offline listening!

**Pull request closed without merging**
