### PR TITLE
Still getting a strange error on MacOS

### PR DESCRIPTION
**Pull request by UkwaA**
Soundcloud Downloader
Found a track
Error downloading filename: None playlist name: None playlist fileNone

Any clue what's going on?

### CODE REVIEW

**Comment by mavieth** [comment]
What is the URL?

**Comment by UkwaA** [comment]
https://soundcloud.com/uiceheidd/moonlight

**Comment by mavieth** [comment]
```
(base) ✔ ~/sc
22:22 $ rm -rf *.mp3
(base) ✔ ~/sc
22:22 $ pip uninstall scdl -y
Uninstalling scdl-1.6.13:
  Successfully uninstalled scdl-1.6.13
(base) ✔ ~/sc
22:22 $ pip install 'git+https://github.com/mavieth/scdl.git@fix-scdl'
Collecting git+https://github.com/mavieth/scdl.git@fix-scdl
  Cloning https://github.com/mavieth/scdl.git (to revision fix-scdl) to /private/var/folders/q_/n7csqb4j4k92y2gqcdvz4hdm0000gn/T/pip-req-build-2l7qe79p
  Running command git clone -q https://github.com/mavieth/scdl.git /private/var/folders/q_/n7csqb4j4k92y2gqcdvz4hdm0000gn/T/pip-req-build-2l7qe79p
  Running command git checkout -b fix-scdl --track origin/fix-scdl
  Switched to a new branch 'fix-scdl'
  Branch 'fix-scdl' set up to track remote branch 'fix-scdl' from 'origin'.
Requirement already satisfied: docopt in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from scdl==1.6.13) (0.6.2)
Requirement already satisfied: mutagen in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from scdl==1.6.13) (1.43.0)
Requirement already satisfied: termcolor in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from scdl==1.6.13) (1.1.0)
Requirement already satisfied: requests in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from scdl==1.6.13) (2.22.0)
Requirement already satisfied: clint in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from scdl==1.6.13) (0.5.1)
Requirement already satisfied: certifi>=2017.4.17 in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from requests->scdl==1.6.13) (2019.9.11)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from requests->scdl==1.6.13) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from requests->scdl==1.6.13) (1.24.2)
Requirement already satisfied: idna<2.9,>=2.5 in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from requests->scdl==1.6.13) (2.8)
Requirement already satisfied: args in /Users/michaelvieth/miniconda/lib/python3.7/site-packages (from clint->scdl==1.6.13) (0.1.0)
Building wheels for collected packages: scdl
  Building wheel for scdl (setup.py) ... done
  Created wheel for scdl: filename=scdl-1.6.13-cp37-none-any.whl size=17542 sha256=6a0ffa3837079f7fdba0b78ca4288d58b8da7637ef2e27f933b784da9a758aaf
  Stored in directory: /private/var/folders/q_/n7csqb4j4k92y2gqcdvz4hdm0000gn/T/pip-ephem-wheel-cache-um_s91ui/wheels/63/87/00/4b7a4cab492e29aa30bdd2cbfe2a25c30f3ac3ca51d6916b77
Successfully built scdl
Installing collected packages: scdl
Successfully installed scdl-1.6.13
(base) ✔ ~/sc
22:22 $ scdl -l 'https://soundcloud.com/uiceheidd/moonlight'
Soundcloud Downloader
Found a track https://soundcloud.com/uiceheidd/moonlight
Downloaded /Users/michaelvieth/sc/moonlight [prod. sidepce].mp3
(base) ✔ ~/sc
```

Try running these 3 commands....


```
pip uninstall scdl -y
pip install 'git+https://github.com/mavieth/scdl.git@fix-scdl'
scdl -l 'https://soundcloud.com/uiceheidd/moonlight'
```

**Comment by mavieth** [comment]
```
$(which python3) -m venv venv
. venv/bin/activate
pip3 install 'git+https://github.com/mavieth/scdl.git@fix-scdl'
which scdl
scdl -l 'https://soundcloud.com/uiceheidd/moonlight'

```

**Comment by UkwaA** [comment]
I'm not sure what I'm reading in that comment?

**Comment by UkwaA** [comment]
$ which scdl
/Library/Frameworks/Python.framework/Versions/3.6/bin/scdl
$ scdl -l https://soundcloud.com/uiceheidd/moonlight
Soundcloud Downloader
Found a track https://soundcloud.com/uiceheidd/moonlight
Error downloading filename: None playlist name: None playlist fileNone

**Comment by mavieth** [comment]
You can run it as a bash script. I added comments. You basically just want to setup a python virutal environment. It looks like the version of python you are using is the one packaged with your mac.

Try this bash script.


```
#!/usr/bin/env bash

# get the correct python 3 version
PYTHON_VER=$(which python3)

# create virtual environment
$PYTHON_VER -m venv venv

# activate virtual environment
source ./venv/bin/activate

# upgrade pip
pip3 install --upgrade pip

# install my branch of SCDL
pip3 install 'git+https://github.com/mavieth/scdl.git@fix-scdl'

# output which SCDL you are calling
which scdl

# download the track
scdl -l 'https://soundcloud.com/uiceheidd/moonlight'

```

**Comment by UkwaA** [comment]
Everything succeeded up until the end where I got the same error as last time. It seems like I may have to reset my Mac or something to get past this. I appreciate the help you've offered this far.

**Comment by mavieth** [comment]
> Everything succeeded up until the end where I got the same error as last time. It seems like I may have to reset my Mac or something to get past this. I appreciate the help you've offered this far.

No problem. You could also try install python 3.7. I am using miniconda [miniconda](https://docs.conda.io/en/latest/miniconda.html).

In my conda environment I am able to run this in my branch `~/dev/scdl` and it works fine.

```
rm -rf build/
rm -rf .egg*
rm -rf dist/
rm -rf *.mp3
pip uninstall scdl -y
python setup.py uninstall
python setup.py install
scdl -l 'https://soundcloud.com/uiceheidd/moonlight'
```

**Comment by UkwaA** [comment]
I poked around a little bit more and realized it's still not running the scdl from the directory where I installed the virtual Python environment in. Sorry to continue this but do you know how to get it to switch from /Library/Frameworks/Python.framework/Versions/3.6/bin/scdl to the new virtual environment?

**Comment by mavieth** [comment]
```
mkdir -p ~/dev/scdl
python3.6 -m venv venv
```

In a new terminal window activate the virtual environment.
```
cd ~/dev/scdl
source ./venv/bin/activate
```

Check that your scdl path is correct
```
which scdl
```
It should output something like 
```
~/dev/scdl/venv/lib/python3.7/site-packages/scdl
```

Check your scdl version (my branch is 1.6.13 and yours should be too
```
scdl --version
```

Try to download
```
scdl -l 'https://soundcloud.com/uiceheidd/moonlight'
```

**Comment by mavieth** [comment]
Python version `3.7.4`

**Comment by mavieth** [comment]
I was seeing the same error when using venv... I was able to work around it by cloning the repo.

```
rm -rf ~/dev/scdl
mkdir -p ~/dev
git clone https://github.com/mavieth/scdl.git ~/dev/scdl
cd ~/dev/scdl
PYTHON_VER=$(which python3)
$PYTHON_VER -m venv venv
```

New terminal window...

```
cd ~/dev/scdl
source venv/bin/activate
pip install --upgrade pip
python setup.py install
scdl -l 'https://soundcloud.com/uiceheidd/moonlight' --debug
```

**Comment by UkwaA** [comment]
Here's the return of the debug 

{'--addtimestamp': False,
 '--addtofile': False,
 '--debug': True,
 '--download-archive': None,
 '--error': False,
 '--extract-artist': False,
 '--flac': False,
 '--help': False,
 '--hide-progress': False,
 '--hidewarnings': False,
 '--max-size': None,
 '--min-size': None,
 '--no-playlist-folder': False,
 '--onlymp3': False,
 '--path': None,
 '--remove': False,
 '--version': False,
 '-C': False,
 '-a': False,
 '-c': False,
 '-f': False,
 '-l': 'https://soundcloud.com/uiceheidd/moonlight',
 '-m': False,
 '-o': None,
 '-p': False,
 '-s': False,
 '-t': False,
 'me': False}
https://api-v2.soundcloud.com/resolve?url=https://soundcloud.com/uiceheidd/moonlight&client_id=a3e059563d7fd3372b49b37f00a00bcf
{'comment_count': 11024, 'full_duration': 178092, 'downloadable': False, 'created_at': '2017-06-15T20:37:29Z', 'description': 'Dance in the Moonlight..I know the mood is right.\n\n\n\nspirdark was here.', 'media': {'transcodings': [{'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:328259792/92e7fc8f-afbd-4d4b-9c78-47e5e9cffc7c/stream/hls', 'preset': 'mp3_0_0', 'duration': 178092, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/mpeg'}, 'quality': 'sq'}, {'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:328259792/fec68fdb-f616-457c-bf27-45495b04613f/stream/hls', 'preset': 'opus_0_0', 'duration': 178092, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/ogg; codecs="opus"'}, 'quality': 'sq'}]}, 'title': 'moonlight [prod. sidepce]', 'publisher_metadata': {'urn': 'soundcloud:tracks:328259792', 'id': 328259792}, 'duration': 178092, 'has_downloads_left': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000233299595-4praio-large.jpg', 'public': True, 'streamable': True, 'tag_list': 'JuiceWRLD Lucid VIBE$', 'download_url': None, 'genre': 'JuiceWRLD', 'id': 328259792, 'reposts_count': 17421, 'state': 'finished', 'label_name': None, 'last_modified': '2020-01-16T06:20:02Z', 'commentable': True, 'policy': 'MONETIZE', 'visuals': None, 'kind': 'track', 'purchase_url': None, 'sharing': 'public', 'uri': 'https://api.soundcloud.com/tracks/328259792', 'secret_token': None, 'download_count': 0, 'likes_count': 614343, 'urn': 'soundcloud:tracks:328259792', 'license': 'all-rights-reserved', 'purchase_title': None, 'display_date': '2017-06-15T20:37:29Z', 'embeddable_by': 'all', 'release_date': None, 'user_id': 132790246, 'monetization_model': 'BLACKBOX', 'waveform_url': 'https://wave.sndcdn.com/w1gtNSwZMLNv_m.json', 'permalink': 'moonlight', 'permalink_url': 'https://soundcloud.com/uiceheidd/moonlight', 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-000310352068-6gufdm-large.jpg', 'city': 'Chicago', 'comments_count': 0, 'country_code': None, 'created_at': '2015-01-13T04:10:09Z', 'creator_subscriptions': [{'product': {'id': 'creator-pro-unlimited'}}], 'creator_subscription': {'product': {'id': 'creator-pro-unlimited'}}, 'description': 'Follow dreams you never have ask', 'followers_count': 1355255, 'followings_count': 76, 'first_name': '', 'full_name': '', 'groups_count': 0, 'id': 132790246, 'kind': 'user', 'last_modified': '2019-10-04T04:20:47Z', 'last_name': '', 'likes_count': 476, 'playlist_likes_count': 15, 'permalink': 'uiceheidd', 'permalink_url': 'https://soundcloud.com/uiceheidd', 'playlist_count': 10, 'reposts_count': None, 'track_count': 97, 'uri': 'https://api.soundcloud.com/users/132790246', 'urn': 'soundcloud:users:132790246', 'username': 'Juice WRLD', 'verified': False, 'visuals': {'urn': 'soundcloud:users:132790246', 'enabled': True, 'visuals': [{'urn': 'soundcloud:visuals:35964549', 'entry_time': 0, 'visual_url': 'https://i1.sndcdn.com/visuals-000132790246-6aRsQL-original.jpg'}]}}, 'playback_count': 47330465}
Found a track
Retrieving more info on the track @ https://api-v2.soundcloud.com/tracks/328259792
Get track response status: 200
{'comment_count': 11024, 'full_duration': 178092, 'downloadable': False, 'created_at': '2017-06-15T20:37:29Z', 'description': 'Dance in the Moonlight..I know the mood is right.\n\n\n\nspirdark was here.', 'media': {'transcodings': [{'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:328259792/92e7fc8f-afbd-4d4b-9c78-47e5e9cffc7c/stream/hls', 'preset': 'mp3_0_0', 'duration': 178092, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/mpeg'}, 'quality': 'sq'}, {'url': 'https://api-v2.soundcloud.com/media/soundcloud:tracks:328259792/fec68fdb-f616-457c-bf27-45495b04613f/stream/hls', 'preset': 'opus_0_0', 'duration': 178092, 'snipped': False, 'format': {'protocol': 'hls', 'mime_type': 'audio/ogg; codecs="opus"'}, 'quality': 'sq'}]}, 'title': 'moonlight [prod. sidepce]', 'publisher_metadata': {'urn': 'soundcloud:tracks:328259792', 'id': 328259792}, 'duration': 178092, 'has_downloads_left': True, 'artwork_url': 'https://i1.sndcdn.com/artworks-000233299595-4praio-large.jpg', 'public': True, 'streamable': True, 'tag_list': 'JuiceWRLD Lucid VIBE$', 'download_url': None, 'genre': 'JuiceWRLD', 'id': 328259792, 'reposts_count': 17421, 'state': 'finished', 'label_name': None, 'last_modified': '2020-01-16T06:20:02Z', 'commentable': True, 'policy': 'MONETIZE', 'visuals': None, 'kind': 'track', 'purchase_url': None, 'sharing': 'public', 'uri': 'https://api.soundcloud.com/tracks/328259792', 'secret_token': None, 'download_count': 0, 'likes_count': 614343, 'urn': 'soundcloud:tracks:328259792', 'license': 'all-rights-reserved', 'purchase_title': None, 'display_date': '2017-06-15T20:37:29Z', 'embeddable_by': 'all', 'release_date': None, 'user_id': 132790246, 'monetization_model': 'BLACKBOX', 'waveform_url': 'https://wave.sndcdn.com/w1gtNSwZMLNv_m.json', 'permalink': 'moonlight', 'permalink_url': 'https://soundcloud.com/uiceheidd/moonlight', 'user': {'avatar_url': 'https://i1.sndcdn.com/avatars-000310352068-6gufdm-large.jpg', 'first_name': '', 'full_name': '', 'id': 132790246, 'kind': 'user', 'last_modified': '2019-10-04T04:20:47Z', 'last_name': '', 'permalink': 'uiceheidd', 'permalink_url': 'https://soundcloud.com/uiceheidd', 'uri': 'https://api.soundcloud.com/users/132790246', 'urn': 'soundcloud:users:132790246', 'username': 'Juice WRLD', 'verified': False, 'city': 'Chicago', 'country_code': None}, 'playback_count': 47330465}
https://api-v2.soundcloud.com/media/soundcloud:tracks:328259792/92e7fc8f-afbd-4d4b-9c78-47e5e9cffc7c/stream/hls?client_id=a3e059563d7fd3372b49b37f00a00bcf
Error downloading filename: None playlist name: None playlist fileNone

once again I can't thank you enough for offering your help through this frustrating process

**Comment by mavieth** [comment]
No worries mate. I was able to reproduce it but not using python 3.7.

I would try installing that and running the same commands. You could also make sure you don't have it installed in a local lib.

```
sudo pip uninstall scdl
pip uninstall scdl
sudo pip3 uninstall scdl
pip3 uninstall scdl
deactivate
sudo pip uninstall scdl
pip uninstall scdl
sudo pip3 uninstall scdl
pip3 uninstall scdl
```

In a new terminal and Python3.7 installed give it another rip.

**Pull request closed without merging**
