### PR TITLE
Fix CLI / FFMPEG

### PR DESCRIPTION
**Pull request by mavieth**
- There was an issue with the FFMPEG commands and the directory it was executing out of. 
- Updated to V2 API urls (`api.soundcloud.com`->`api-v2.soundcloud.com`). This may have been the cause for the 401 errors.

### CODE REVIEW

**Comment by flyingrub** [comment]
I remember having some issue when trying to move all the API endpoint to the v2 url. Did you try them all ?

**Comment by mavieth** [comment]
> I remember having some issue when trying to move all the API endpoint to the v2 url. Did you try them all ?

I did not. I can give it a try. It may be worth adding some unit tests.

**Comment by flyingrub** [comment]
I did merge some of your fixes on master but not the api endpoint changes as you did not test them yet.

**Comment by flyingrub** [comment]
The api endpoint changes are now done

**Pull request closed without merging**
